defaults: &defaults

  check_scheduler: CheckScheduler

  # how should they be scheduled and run?
  check_runner: EventmachineCheckRunner
  check_runner_connect_timeout: 15
  check_runner_inactivity_timeout: 60

  # how are check results converted into properties?
  check_marshaller: EnvironmentAwareCheckMarshaller

  # how/where are check results published?
  check_logger: KeenCheckLogger
  keen:
    project_id: <%= ENV['KEEN_PROJECT_ID'] %>
    write_key: <%= ENV['KEEN_WRITE_KEY'] %>
    read_key: <%= ENV['KEEN_READ_KEY'] %>
    master_key: <%= ENV['KEEN_MASTER_KEY'] %>
    collection: <%= ENV['KEEN_COLLECTION'] || 'checks' %>

  slack: 
    channel: <%= ENV['SLACK_CHANNEL'] %>
    username: <%= ENV['SLACK_USERNAME'] || 'Pingpong' %>
    icon: <%= ENV['SLACK_ICON'] %>
    warn_color: '<%= ENV['WARN_COLOR'] || '#E2E541' %>'
    bad_color: '<%= ENV['BAD_COLOR'] || '#F25656' %>'

  # by default a web worker will run checks
  skip_checks: <%= ENV['SKIP_CHECKS'] %>

  # by default a web worker will run pushpop jobs
  skip_pushpop: <%= ENV['SKIP_PUSHPOP'] %>

  # be default don't send email
  skip_email: <%= ENV['SKIP_EMAIL'] %>
  to_email_address: <%= ENV['TO_EMAIL_ADDRESS'] %>
  from_email_address: <%= ENV['FROM_EMAIL_ADDRESS'] %>

  # add http authentication
  http_username: <%= ENV['HTTP_USERNAME'] %>
  http_password: <%= ENV['HTTP_PASSWORD'] %>

development:
  <<: *defaults

  environment:
    region: <%= ENV['REGION'] || 'local' %>
    location: <%= ENV['LOCATION'] || 'San Francisco, CA, US' %>
    hostname: <%= ENV['HOSTNAME'] || (`hostname` rescue nil) %>

test:
  <<: *defaults

  environment:
    region: test-region
    location: test-location
    hostname: test-hostname

  keen:
    project_id: test-project-id
    write_key: test-write-key
    read_key: test-read-key
    collection: test-collection

  skip_checks: true
  skip_pushpop: true

  http_username: foo
  http_password: bar

production:
  <<: *defaults

  # add environment specific configs here if you want them in your properties
  environment:
    region: <%= ENV['REGION'] || 'heroku-us-east' %>
    location: <%= ENV['LOCATION'] || 'Northern Virginia, US' %>
    hostname: <%= ENV['HOSTNAME'] || (`hostname` rescue nil) %>

