development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: pingpong_dev

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: pingpong_test

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: pingpong
